package com.notesharing.model;
// Generated 2018-4-23 20:08:03 by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CollectPhotos generated by hbm2java
 */
@Entity
@Table(name = "collect_photos")
public class CollectPhotos implements java.io.Serializable {

	private int userid;
	private Integer collectid;
	private Date collectdate;

	public CollectPhotos() {
	}

	public CollectPhotos(int userid) {
		this.userid = userid;
	}

	public CollectPhotos(int userid, Integer collectid, Date collectdate) {
		this.userid = userid;
		this.collectid = collectid;
		this.collectdate = collectdate;
	}

	@Id

	@Column(name = "USERID", unique = true, nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "COLLECTID")
	public Integer getCollectid() {
		return this.collectid;
	}

	public void setCollectid(Integer collectid) {
		this.collectid = collectid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COLLECTDATE", length = 0)
	public Date getCollectdate() {
		return this.collectdate;
	}

	public void setCollectdate(Date collectdate) {
		this.collectdate = collectdate;
	}

}
