package com.notesharing.model;
// Generated 2018-4-23 20:08:03 by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CollectPhoto generated by hbm2java
 */
@Entity
@Table(name = "collect_photo")
public class CollectPhoto implements java.io.Serializable {

	private int userid;
	private String collectpath;
	private Date collectdate;

	public CollectPhoto() {
	}

	public CollectPhoto(int userid) {
		this.userid = userid;
	}

	public CollectPhoto(int userid, String collectpath, Date collectdate) {
		this.userid = userid;
		this.collectpath = collectpath;
		this.collectdate = collectdate;
	}

	@Id

	@Column(name = "USERID", unique = true, nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	@Column(name = "COLLECTPATH")
	public String getCollectpath() {
		return this.collectpath;
	}

	public void setCollectpath(String collectpath) {
		this.collectpath = collectpath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COLLECTDATE", length = 0)
	public Date getCollectdate() {
		return this.collectdate;
	}

	public void setCollectdate(Date collectdate) {
		this.collectdate = collectdate;
	}

}
