package com.notesharing.model;
// Generated 2018-4-23 20:08:03 by Hibernate Tools 4.0.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Photos generated by hbm2java
 */
@Entity
@Table(name = "photos")
public class Photos implements java.io.Serializable {

	private int photosid;// 图集id
	private String author;// 作者
	private String label;//
	private String introduce;// 介绍
	private Integer praise;// 点赞
	private Date uploaddate;// 上传时间
	private int count;// 数量
	private String address;// 保存地址
	private String tag1;
	private String tag2;
	private String tag3;

	public Photos() {
	}

	public Photos(int photosid, String author) {
		this.photosid = photosid;
		this.author = author;
	}

	public Photos(int photosid, String author, String label, String introduce, Integer praise, Date uploaddate) {
		this.photosid = photosid;
		this.author = author;
		this.label = label;
		this.introduce = introduce;
		this.praise = praise;
		this.uploaddate = uploaddate;
	}

	@Column(name = "ADDRESS")
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "COUNT")
	public int getCount() {
		return count;
	}

	public void setCount(int count) {
		this.count = count;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "PHOTOSID", unique = true, nullable = false)
	public int getPhotosid() {
		return this.photosid;
	}

	public void setPhotosid(int photosid) {
		this.photosid = photosid;
	}

	@Column(name = "AUTHOR", nullable = false)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Column(name = "LABEL")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "INTRODUCE", length = 65535)
	public String getIntroduce() {
		return this.introduce;
	}

	public void setIntroduce(String introduce) {
		this.introduce = introduce;
	}

	@Column(name = "PRAISE")
	public Integer getPraise() {
		return this.praise;
	}

	public void setPraise(Integer praise) {
		this.praise = praise;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPLOADDATE", length = 0)
	public Date getUploaddate() {
		return this.uploaddate;
	}

	public void setUploaddate(Date uploaddate) {
		this.uploaddate = uploaddate;
	}

	@Column(name = "TAG1")
	public String getTag1() {
		return tag1;
	}

	public void setTag1(String tag1) {
		this.tag1 = tag1;
	}

	@Column(name = "TAG2")
	public String getTag2() {
		return tag2;
	}

	public void setTag2(String tag2) {
		this.tag2 = tag2;
	}

	@Column(name = "TAG3")
	public String getTag3() {
		return tag3;
	}

	public void setTag3(String tag3) {
		this.tag3 = tag3;
	}

}
