package com.notesharing.model;
// Generated 2018-4-23 20:08:03 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Photo generated by hbm2java
 */
@Entity
@Table(name = "photo")
public class Photo implements java.io.Serializable {

	private int photoid;
	private Integer praise;
	private Integer photosid;
	private String comment;
	private String address;

	public Photo() {
	}

	public Photo(int photoid) {
		this.photoid = photoid;
	}

	public Photo(int photoid, Integer praise, Integer photosid, String comment) {
		this.photoid = photoid;
		this.praise = praise;
		this.photosid = photosid;
		this.comment = comment;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "PHOTOID", unique = true, nullable = false)
	public int getPhotoid() {
		return this.photoid;
	}

	public void setPhotoid(int photoid) {
		this.photoid = photoid;
	}

	@Column(name = "ADDRESS")
	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "PRAISE")
	public Integer getPraise() {
		return this.praise;
	}

	public void setPraise(Integer praise) {
		this.praise = praise;
	}

	@Column(name = "PHOTOSID")
	public Integer getPhotosid() {
		return this.photosid;
	}

	public void setPhotosid(Integer photosid) {
		this.photosid = photosid;
	}

	@Column(name = "COMMENT", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
