package com.notesharing.model;
// Generated 2018-4-23 20:08:03 by Hibernate Tools 4.0.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PhotosComment generated by hbm2java
 */
@Entity
@Table(name = "photos_comment")
public class PhotosComment implements java.io.Serializable {

	private int id;
	private int photosid;
	private String datatime;
	private String comment;
	private String u_name;
	private String u_headportrait;// 头像地址

	public PhotosComment() {
	}

	public PhotosComment(int id, int photosid) {
		this.id = id;
		this.photosid = photosid;
	}

	public PhotosComment(int id, int photosid, String datatime, String comment) {
		this.id = id;
		this.photosid = photosid;
		this.datatime = datatime;
		this.comment = comment;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "HEADPORTRAIT", nullable = true, length = 100)
	public String getU_headportrait() {
		return u_headportrait;
	}

	public void setU_headportrait(String u_headportrait) {
		this.u_headportrait = u_headportrait;
	}

	@Column(name = "UNAME", nullable = false)
	public String getU_name() {
		return u_name;
	}

	public void setU_name(String u_name) {
		this.u_name = u_name;
	}

	@Column(name = "PHOTOSID", nullable = false)
	public int getPhotosid() {
		return this.photosid;
	}

	public void setPhotosid(int photosid) {
		this.photosid = photosid;
	}

	// @Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATATIME", length = 65535)
	public String getDatatime() {
		return this.datatime;
	}

	public void setDatatime(String datatime) {
		this.datatime = datatime;
	}

	@Column(name = "COMMENT", length = 65535)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
